# Generated by Django 3.0.8 on 2020-07-24 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_listing_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_bid_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_is_deleted', models.BooleanField(default=False)),
                ('watchlist_listing', models.ManyToManyField(blank=True, related_name='my_watchlist_listing', to='auctions.Listing')),
                ('watchlist_owner', models.ManyToManyField(blank=True, related_name='watchlist_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
