# Generated by Django 3.0.8 on 2020-07-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200724_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_bidder',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_bidder',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='my_biddings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
